# Generated by Django 4.2.2 on 2023-06-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_id', models.IntegerField()),
                ('prev', models.CharField(max_length=20)),
                ('pres', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=60)),
                ('fname', models.CharField(max_length=60)),
                ('mi', models.CharField(blank=True, max_length=2, null=True)),
                ('address', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'owners',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TempoBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev', models.CharField(db_column='Prev', max_length=40)),
                ('client', models.CharField(db_column='Client', max_length=30)),
            ],
            options={
                'db_table': 'tempo_bill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
